name = "LowRankVortex"
uuid = "fdf095b8-6f21-420b-9d49-8e692abb03d1"
authors = ["mleprovost <mathow@g.ucla.edu>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GaussianMixtures = "cc18c42c-b769-54ff-9e2a-b28141a64aae"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
NamedColors = "51fcb6bd-ecd8-522c-95bc-4099d1d03463"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PotentialFlow = "73af2aaf-3f58-5b29-82a9-435ecf827f5b"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TransportBasedInference = "bdf749b0-1400-4207-80d3-e689c0e3f03d"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
